pebble:
  # default ".peb" to "":
  suffix:
  cache: false
spring:
  application:
    name: ICN_Back
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase

server:
  port: 8082
  servlet:
    context-path: /api
